#!/bin/bash
# Create snapshot and delete backups of 7 days old
# Should be placed in /var/scripts/
# A list of snapshots per VM is available in: /var/scripts/snapshot-list
# Due to an unknown bug the snapshots are not visible in virtualbox's UI

# Vars
NOW=$(date +%d-%m-%y)
DAYS_AGO=$(date -d "7 days ago"  +"%d-%m-%y")
SNAPSHOT_NAME="$NOW"
SCRIPTS="/var/scripts"
SNAPSHOTDIR="$SCRIPTS/snapshot-list"
VBOXUSR=""

# VM's
VM1=""
VM2=""
VM3=""

# Snapshot take and delete per VM
sudo -H -b -u "$VBOXUSR" VBoxManage snapshot "$VM1" delete "$DAYS_AGO"
sudo -H -b -u "$VBOXUSR" VBoxManage snapshot "$VM1" take "$SNAPSHOT_NAME"

# List the current snapshots in a file
mkdir -p "$SCRIPTS"
mkdir -p "$SNAPSHOTDIR"

VM1LIST=$(vboxmanage snapshot "$VM1" list)
echo "$VM1LIST" > "$SNAPSHOTDIR"/"$VM1"

# Start all vm's as safety, comment out if you dont have the startup script
/etc/init.d/StartVMs start
